### ISSUE TITLE
Print warning when selected runtime version is/will be going EOS

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/php#264]
Similar to the work done in the [Node.js](https://github.com/paketo-buildpacks/node-engine/blob/14c9ba932f912a35654d011a61ba2298cd942824/log_emitter.go#L33) and Go Buildpacks, we should start printing deprecation messages in all PHP buildpacks that let users select a runtime version when a dependency is/will be EOS.

**Comment by fg-j** [comment]
This will require changes to buildpacks in the PHP language family that install dependencies:
- [ ] PHP dist - Already resolved because the buildpack [uses the `packit.scribe.LogEmitter`](https://github.com/paketo-buildpacks/php-dist/blob/a885e348c3207d122ca7a625ac48c4db02525e37/build.go#L54), which supports this automatically)
- [ ] PHP composer – Blocked pending a rewrite of the composer buildpack to use packit. Once it's rewritten, it can use the `packit.scribe.LogEmitter` and get this functionality for free.
- [ ] HTTPD – Resolved since this buildpack [uses the `packit.scribe.LogEmitter`](https://github.com/paketo-buildpacks/httpd/blob/064a5565c6756320fc978ad29e978eade6541578/build.go#L55)
- [ ] NGINX – Resolved since this buildpack [uses the `packit.scribe.LogEmitter`](https://github.com/paketo-buildpacks/nginx/blob/5f4772512393e509d6447601e4a45122861eaeb7/build.go#L61)

**Comment by fg-j** [comment]
@paketo-buildpacks/php-maintainers is this still an issue now that the PHP rewrite has been completed?

**Comment by sophiewigmore** [comment]
Yes! The new Composer CNB uses the `packit.scribe.LogEmitter` and leverages `SelectedDependency` which should solve this issue.
