### ISSUE TITLE
PHP Buildpack starting 1.2.0 is not compatible with api 0.7

### ISSUE THREAD

**Issue by cxhrouet** [paketo-buildpacks/php#587]
buildpack.toml of the PHP Buildpack is referencing api 0.7 but two underlying buildpacks (httpd and nginx) are referencing api 0.8, thus the PHP Buildpack cannot run on a platform supporting only api 0.7.

## Expected Behavior
buildpack.toml should reference an api version consistent with the platform which is required to run it.

## Current Behavior
PHP buildpack starting 1.2.0 cannot run on a platform limited to api 0.7 even if its buildpack.toml is referencing api 0.7

## Possible Solution
Update buildpack.toml to api 0.8

## Steps to Reproduce
Try to build an image with PHP Buildpack 1.2.0 or 1.3.0 on a platform not supporting api 0.8. In my case it is Tanzu Build Service 1.5.2 which is shipped with kpack 0.5.4

## Motivations
I'm repackaging the PHP Buildpack to add Oracle support. I was relying on the buildpack.toml to assure api compatibility with the platform whenever there is a new release of the buildpack on Github.

**Comment by sophiewigmore** [comment]
@cxhrouet Thank you for letting us know about this. The HTTPD and Nginx buildpacks have been rolled back to API 0.7 and released, so the latest PHP buildpack ([v1.4.0](https://github.com/paketo-buildpacks/php/releases/tag/v1.4.0)) should contain these versions. Can you test it out and let me know if your issue is resolved?

**Comment by sophiewigmore** [comment]
Closing this out but please feel free to reopen if this issue is still occurring for you with new buildpack versions.
