### ISSUE TITLE
unable to use php buildpack to compile for php 7.4

### ISSUE THREAD

**Issue by dmitry-mightydevops** [paketo-buildpacks/php#666]
## Expected Behavior

Unable to compile using pinned version of the php buildpack:0.11
Please review exact details in https://github.com/buildpacks/pack/issues/1649

## Current Behavior

Exits with error

```sh
ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/796e6b77717174746e75:latest: loading image "pack.local/builder/796e6b77717174746e75:latest". first error: embedded daemon response: max depth exceeded]
```

## Steps to Reproduce

https://github.com/buildpacks/pack/issues/1649

## Motivations

I'm trying to use pack cli to come up with a local image. The code is not compatible with PHP 8.x so I have to use older version of the php buildpack (particularly 0.11).

**Comment by sophiewigmore** [comment]
Hey @dmitry-mightydevops, as indicated from the pack issue you linked, I think that you are hitting the `max depth` issue because you are using the `paketobuildpacks/builder:0.2.256-full`, which includes every buildpack we support in Paketo, and then **also** passing an extra buildpack via `--buildpack gcr.io/paketo-buildpacks/php:2.4`.

The resolution would be to instead use our buildpackless builder in your build. This has the same "full" base image compatible with PHP, but includes no buildpacks. By passing the buildpack you want to use, you should avoid the max depth issue.

**Comment by sophiewigmore** [comment]
Hey @dmitry-mightydevops, as indicated from the pack issue you linked, I think that you are hitting the `max depth` issue because you are using the `paketobuildpacks/builder:0.2.256-full`, which includes every buildpack we support in Paketo, and then **also** passing an extra buildpack via `--buildpack gcr.io/paketo-buildpacks/php:2.4`.

The resolution would be to instead use our buildpackless builder in your build. This has the same "full" base image compatible with PHP, but includes no buildpacks. By passing the buildpack you want to use, you should avoid the max depth issue.


The following should work:
```
pack build app --path=$(pwd) --builder gcr.io/paketo-buildpacks/builder:buildpackless-full --buildpack gcr.io/paketo-buildpacks/php:0.11
```

If this does not work, please let us know what the error is that you're seeing

**Comment by sophiewigmore** [comment]
@dmitry-mightydevops any updates here?

**Comment by dmitry-mightydevops** [comment]
@sophiewigmore will respond by EOW with details. Sorry for the delay!

**Comment by sophiewigmore** [comment]
Hey! Is still an issue for you?
